language: java
jdk:
#   - oraclejdk7	#xtext 2.11 requires jdk8
   - oraclejdk8
install: true
before_script:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - sleep 3
script:
  - mvn clean install
after_failure:
  - cat tests/org.jnario.tests/target/work/data/.metadata/.log
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  target_branch: p2-deploy